spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/lago
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}   # MailHog SMTP para desarrollo
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:false}
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  jackson:
    time-zone: UTC
  task:
    scheduling:
      time-zone: America/Argentina/Cordoba

app:
  defaultCapacity: 30
  admin:
    username: admin
    password: admin123
  mail:
    from: ${APP_MAIL_FROM:noreply@lago-escondido.com}
    fromName: ${APP_MAIL_FROM_NAME:Lago Escondido}
    enabled: ${APP_MAIL_ENABLED:true}

server:
  port: 8080

# application.yml
logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
    url: /v3/api-docs


