# Configuración base - se sobrescribe con profiles específicos
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  application:
    name: lago-escondido-reservas

# Configuración común para todos los profiles
app:
  version: ${APP_VERSION:1.0.0}
  environment: ${APP_ENVIRONMENT:development}

# Configuración por defecto (será sobrescrita por profiles)
server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO


